//
// Generated file, do not edit! Created by nedtool 4.6 from connReq.msg.
//

#ifndef _CONNREQ_M_H_
#define _CONNREQ_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>connReq.msg:8</tt> by nedtool.
 * <pre>
 * //
 * // Author: Ahmad R. Dhaini
 * // CMPS 284 - Computer Networks
 * // Fall 2015-16
 * // American University of Beirut
 * //
 * message connReq
 * {
 *     int packetSize;
 *     simtime_t pcktTimeStamp;
 * }
 * </pre>
 */
class connReq : public ::cMessage
{
  protected:
    int packetSize_var;
    simtime_t pcktTimeStamp_var;

  private:
    void copy(const connReq& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const connReq&);

  public:
    connReq(const char *name=NULL, int kind=0);
    connReq(const connReq& other);
    virtual ~connReq();
    connReq& operator=(const connReq& other);
    virtual connReq *dup() const {return new connReq(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getPacketSize() const;
    virtual void setPacketSize(int packetSize);
    virtual simtime_t getPcktTimeStamp() const;
    virtual void setPcktTimeStamp(simtime_t pcktTimeStamp);
};

inline void doPacking(cCommBuffer *b, connReq& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, connReq& obj) {obj.parsimUnpack(b);}


#endif // ifndef _CONNREQ_M_H_

