//
// Generated file, do not edit! Created by nedtool 4.6 from SELF.msg.
//

#ifndef _SELF_M_H_
#define _SELF_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>SELF.msg:8</tt> by nedtool.
 * <pre>
 * //
 * // Author: Ahmad R. Dhaini
 * // CMPS 284 - Computer Networks
 * // Fall 2015-16
 * // American University of Beirut
 * //
 * message SELF
 * {
 *     int packet_size;
 *     simtime_t pcktTimeStamp;
 * }
 * </pre>
 */
class SELF : public ::cMessage
{
  protected:
    int packet_size_var;
    simtime_t pcktTimeStamp_var;

  private:
    void copy(const SELF& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SELF&);

  public:
    SELF(const char *name=NULL, int kind=0);
    SELF(const SELF& other);
    virtual ~SELF();
    SELF& operator=(const SELF& other);
    virtual SELF *dup() const {return new SELF(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getPacket_size() const;
    virtual void setPacket_size(int packet_size);
    virtual simtime_t getPcktTimeStamp() const;
    virtual void setPcktTimeStamp(simtime_t pcktTimeStamp);
};

inline void doPacking(cCommBuffer *b, SELF& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SELF& obj) {obj.parsimUnpack(b);}


#endif // ifndef _SELF_M_H_

