//
// Generated file, do not edit! Created by nedtool 4.6 from statusUpdate.msg.
//

#ifndef _STATUSUPDATE_M_H_
#define _STATUSUPDATE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>statusUpdate.msg:2</tt> by nedtool.
 * <pre>
 * message statusUpdate
 * {
 *     int ServerId;
 *     int AvailableSpace;
 * 
 * }
 * </pre>
 */
class statusUpdate : public ::cMessage
{
  protected:
    int ServerId_var;
    int AvailableSpace_var;

  private:
    void copy(const statusUpdate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const statusUpdate&);

  public:
    statusUpdate(const char *name=NULL, int kind=0);
    statusUpdate(const statusUpdate& other);
    virtual ~statusUpdate();
    statusUpdate& operator=(const statusUpdate& other);
    virtual statusUpdate *dup() const {return new statusUpdate(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getServerId() const;
    virtual void setServerId(int ServerId);
    virtual int getAvailableSpace() const;
    virtual void setAvailableSpace(int AvailableSpace);
};

inline void doPacking(cCommBuffer *b, statusUpdate& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, statusUpdate& obj) {obj.parsimUnpack(b);}


#endif // ifndef _STATUSUPDATE_M_H_

